// Nivel5Mundo2/clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {
  public editoras: Array<Editora> = []
  public livros: Array<Livro> = []


  constructor(private servEditora: ControleEditoraService, private servLivros: ControleLivrosService) {}

  excluir = async (codigo: string)=>{
    await this.servLivros.excluir(codigo).then(()=>{
      this.servLivros.obterLivros().then((resultado)=>{
        this.livros = resultado
      })
    })
  }

  obterNome = (codEditora: number)=>{
    return this.servEditora.getNomeEditora(Number(codEditora))
  }

  ngOnInit() {
    this.editoras = this.servEditora.getEditoras()
    this.servLivros.obterLivros().then((resultado)=>{
      this.livros = resultado
    })
  }
}

<main class="container">
  <h1 class="my-3">Catálogo de Livros</h1>
  <table class="table table-success table-striped">
    <thead>
      <tr class="table-dark">
        <th>Título</th>
        <th>Resumo</th>
        <th>Editora</th>
        <th>Autores</th>
      </tr>
    </thead>
    <tbody>
      <tr class="table-light" *ngFor="let livro of livros">
        <td>
          <p>
            {{ livro.titulo }}
          </p>
          <button class="btn btn-danger" (click)="excluir(livro.codigo)">
            Excluir
          </button>
        </td>
        <td>{{ livro.resumo }}</td>
        <td>{{ obterNome(livro.codEditora) }}</td>
        <td>
          <ul>
            <li *ngFor="let autor of livro.autores">{{ autor }}</li>
          </ul>
        </td>
      </tr>
    </tbody>
  </table>
</main>

// Nivel5Mundo2/clientes/livros-react/src/LivroLista.js
import { useState, useEffect } from 'react';
import ControleEditora from './controle/ControleEditora';
import ControleLivro from './controle/ControleLivros';

const controleLivro = new ControleLivro();
const controleEditora = new ControleEditora();

const LinhaLivro = (props) => {
  const { livro, excluir } = props;
  const nomeEditora = controleEditora.getNomeEditora(livro.codEditora);

  return (
    <tr className='table-light'>
      <td>
        <p>
        {livro.titulo} 
        </p>
        <button className='btn btn-danger' onClick={() => excluir(livro.codigo)}>Excluir</button>
      </td>
      <td >{livro.resumo}</td>
      <td>{nomeEditora}</td>
      <td>
        <ul>
          {livro.autores.map((autor, index) => (
            <li key={index}>{autor}</li>
          ))}
        </ul>
      </td>
    </tr>
  );
};

const LivroLista =() => {
  const [livros, setLivros] = useState([]);
  const [carregado, setCarregado] = useState(false);

  useEffect(()=>{
    controleLivro.obterLivros().then((resultado)=>{
      setLivros(resultado);
      setCarregado(true)
    })
  },[carregado])

  const excluir = async (codigo) => {
    await controleLivro.excluir(codigo).then(()=>{
      setCarregado(false);
    });
  };

  return (
    <main className='container'>
      <h1 className='my-3'>Catálogo de Livros</h1>
      <table className='table table-success table-striped'>
        <thead>
          <tr className=' table-dark'>
            <th>Título</th>
            <th>Resumo</th>
            <th>Editora</th>
            <th>Autores</th>
          </tr>
        </thead>
        <tbody>
          {livros.map((livro, index) => (
            <LinhaLivro
              key={index}
              livro={livro}
              excluir={excluir}
            />
          ))}
        </tbody>
      </table>
    </main>
  );
}

export default LivroLista
